/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author RODRIGO
 */
public class carretera extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    FondoPanel2 fondo2 = new FondoPanel2();    
    private Connection con;
    Connect  conectar = new Connect();
    Statement st;
    ResultSet rs;
    Statement st2;
    ResultSet rs2;
    PreparedStatement ps;
    /**
     * Creates new form carretera
     */
    public carretera() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        carPai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        carCar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        carCat = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jPanel1 = new FondoPanel2();
        jButton2 = new javax.swing.JButton();
        cmdBuscarCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATOS  CARRETERA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        carId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIdActionPerformed(evt);
            }
        });
        carId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carIdKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");

        carNom.setEnabled(false);
        carNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carNomActionPerformed(evt);
            }
        });
        carNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carNomKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAIS:");

        carPai.setEnabled(false);
        carPai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carPaiKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUMERO DE CARRILES");

        carCar.setEnabled(false);
        carCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carCarActionPerformed(evt);
            }
        });
        carCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carCarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID DE CATEGORIA");

        carCat.setEnabled(false);
        carCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carCatActionPerformed(evt);
            }
        });
        carCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carCatKeyTyped(evt);
            }
        });

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.setEnabled(false);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdModificar.setBackground(new java.awt.Color(255, 255, 0));
        cmdModificar.setText("Modificar");
        cmdModificar.setEnabled(false);
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdCancelar.setBackground(new java.awt.Color(255, 255, 0));
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systems/imgBorrar.png"))); // NOI18N
        cmdBorrar.setEnabled(false);
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdBuscar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        cmdBuscarCat.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscarCat.setText("...");
        cmdBuscarCat.setEnabled(false);
        cmdBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(carNom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(carId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(carPai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(carCar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(carCat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdBuscarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(cmdBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdGuardar)
                .addGap(44, 44, 44)
                .addComponent(cmdModificar)
                .addGap(61, 61, 61)
                .addComponent(cmdCancelar)
                .addGap(51, 51, 51)
                .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(carId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(carPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(carCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(carCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscarCat))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIdActionPerformed

    private void carNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carNomActionPerformed

    private void carCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carCarActionPerformed

    private void carCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carCatActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        if (carNom.getText().trim().equals("") && carPai.getText().trim().equals("") && carCar.getText().trim().equals("") && carCat.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Guardar esta información?", "Carretera", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String insercion = "insert into carretera values(?,?,?,?,?)";
                    ps = (PreparedStatement) con.prepareStatement(insercion);
                    ps.setString(1, carId.getText().trim());
                    ps.setString(2, carNom.getText().toUpperCase().trim());
                    ps.setString(3, carPai.getText().toUpperCase().trim());
                    ps.setString(4, carCar.getText().trim());
                    ps.setString(5, carCat.getText().trim());
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:

        if (carNom.getText().trim().equals("") && carPai.getText().trim().equals("") && carCar.getText().trim().equals("") && carCat.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Modificar esta información?", "Carretera", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String modificacion = "update carretera set nombre='" + carNom.getText().toUpperCase().trim() + "', pais='" + carPai.getText().toUpperCase().trim() + "', numCarriles='" + carCar.getText().trim() + "', idcategoria='" + carCat.getText().trim()  + "' where idcarretera='"+carId.getText().trim() + "'";
                    ps = (PreparedStatement) con.prepareStatement(modificacion);
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro Modificado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        // TODO add your handling code here:
        alCancelar();
    }//GEN-LAST:event_cmdCancelarActionPerformed
    public void alCancelar()
    {
        cmdCancelar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdModificar.setEnabled(false);
        cmdBuscar.setEnabled(true);
        cmdBorrar.setEnabled(false);
        carNom.setEnabled(false);
        carId.setEnabled(true);
        carPai.setEnabled(false);
        carCar.setEnabled(false);
        carCat.setEnabled(false);
        carId.setText("");
        carNom.setText("");
        carPai.setText("");
        carCar.setText("");
        carCat.setText("");
    }
    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Seguro quiere eliminar este registro?", "Carretera", JOptionPane.YES_NO_OPTION)==0)
        {
            try
            {
                con=conectar.getConexion();
                String eliminacion = "delete from carretera where idcarretera='" + carId.getText().trim() + "'" ;
                ps = (PreparedStatement) con.prepareStatement(eliminacion);
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado...");
                alCancelar();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        if(carId.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese un numero de ID");
        }else{
            String busqueda = "select * from Carretera where idCarretera=" + carId.getText().trim();
            try
            {
                con=conectar.getConexion();
                st=(Statement) con.createStatement();
                st2=(Statement) con.createStatement();
                rs=st.executeQuery(busqueda);
                while (rs.next())
                {
                    encontrado = true;
                    cmdModificar.setEnabled(true);
                    cmdGuardar.setEnabled(false);
                    cmdBorrar.setEnabled(true);
                    carNom.setText(rs.getString("nombre"));
                    carPai.setText(rs.getString("pais"));
                    carCar.setText(rs.getString("numCarriles"));
                    carCat.setText(rs.getString("idcategoria"));
                    carId.setText(rs.getString("idCarretera"));
                    rs2=st2.executeQuery("Select * from categoria where idcategoria="+carId.getText().trim());
                    while (rs2.next())
                    {
                        carCat.setText(rs2.getString("idcategoria"));

                    }                    
                }
                con.close();
                cmdCancelar.setEnabled(true);
                cmdBuscar.setEnabled(false);
                carId.setEnabled(false);
                carNom.setEnabled(true);
                carPai.setEnabled(true);
                carCar.setEnabled(true);
                if (encontrado == false)
                    cmdGuardar.setEnabled(true);
                    cmdBuscarCat.setEnabled(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }

    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicio abrir = new inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarCatActionPerformed
        // TODO add your handling code here:
       buscarCategoria buscaCategoria = new buscarCategoria();
       buscaCategoria.setVisible(true);        
    }//GEN-LAST:event_cmdBuscarCatActionPerformed

    private void carNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carNomKeyTyped
        // TODO add your handling code here:       
    }//GEN-LAST:event_carNomKeyTyped

    private void carPaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carPaiKeyTyped
        // TODO add your handling code here:
        char letter = evt.getKeyChar();
        if((letter<'a'||letter>'z')&&(letter<'A'||letter>'Z')){
            evt.consume();
        }         
    }//GEN-LAST:event_carPaiKeyTyped

    private void carIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carIdKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_carIdKeyTyped

    private void carCarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carCarKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_carCarKeyTyped

    private void carCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carCatKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_carCatKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carretera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carretera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carretera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carretera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carretera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carCar;
    public static javax.swing.JTextField carCat;
    private javax.swing.JTextField carId;
    private javax.swing.JTextField carNom;
    private javax.swing.JTextField carPai;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdBuscarCat;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/1.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
    
    class FondoPanel2 extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/2.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
}
