/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author RODRIGO
 */
public class comunidad extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    FondoPanel2 fondo2 = new FondoPanel2();   
    private Connection con;
    Connect  conectar = new Connect();

    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form comunidad
     */
    public comunidad() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comKmCar = new javax.swing.JTextField();
        comKmIni = new javax.swing.JTextField();
        comKmFin = new javax.swing.JTextField();
        cmdBuscar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        jPanel1 = new FondoPanel2();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMUNIDADES");

        comId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comIdActionPerformed(evt);
            }
        });
        comId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comIdKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");

        comNom.setEnabled(false);
        comNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNomActionPerformed(evt);
            }
        });
        comNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comNomKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KM DE CARRETERA:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KM DE INICIO:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KM DE FIN:");

        comKmCar.setEnabled(false);
        comKmCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comKmCarKeyTyped(evt);
            }
        });

        comKmIni.setEnabled(false);
        comKmIni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comKmIniKeyTyped(evt);
            }
        });

        comKmFin.setEnabled(false);
        comKmFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comKmFinKeyTyped(evt);
            }
        });

        cmdBuscar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systems/imgBorrar.png"))); // NOI18N
        cmdBorrar.setEnabled(false);
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdCancelar.setBackground(new java.awt.Color(255, 255, 0));
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdModificar.setBackground(new java.awt.Color(255, 255, 0));
        cmdModificar.setText("Modificar");
        cmdModificar.setEnabled(false);
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.setEnabled(false);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comNom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(comKmCar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comKmIni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(comKmFin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(cmdBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)))
                .addGap(87, 87, 87))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cmdGuardar)
                .addGap(18, 18, 18)
                .addComponent(cmdModificar)
                .addGap(32, 32, 32)
                .addComponent(cmdCancelar)
                .addGap(18, 18, 18)
                .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comKmCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comKmIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comKmFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comIdActionPerformed

    private void comNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comNomActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        if(comId.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese un numero de ID");
        }else{
            String busqueda = "select * from comunidad where idcomunidad=" + comId.getText().trim();
            try
            {
                con=conectar.getConexion();
                st=(Statement) con.createStatement();
                rs=st.executeQuery(busqueda);
                while (rs.next())
                {
                    encontrado = true;
                    cmdModificar.setEnabled(true);
                    cmdGuardar.setEnabled(false);
                    cmdBorrar.setEnabled(true);
                    comNom.setText(rs.getString("nombre"));
                    comKmCar.setText(rs.getString("kmCarretera"));
                    comKmIni.setText(rs.getString("kmInicio"));
                    comKmFin.setText(rs.getString("kmFin"));                
                }
                con.close();
                cmdCancelar.setEnabled(true);
                cmdBuscar.setEnabled(false);
                comId.setEnabled(false);
                comNom.setEnabled(true);
                comKmCar.setEnabled(true);
                comKmIni.setEnabled(true);
                comKmFin.setEnabled(true);
                if (encontrado == false)
                cmdGuardar.setEnabled(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }            
        }
        

    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Seguro quiere eliminar este registro?", "Comunidad", JOptionPane.YES_NO_OPTION)==0)
        {
            try
            {
                con=conectar.getConexion();
                String eliminacion = "delete from comunidad where idcomunidad='" + comId.getText().trim() + "'" ;
                ps = (PreparedStatement) con.prepareStatement(eliminacion);
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado...");
                alCancelar();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        // TODO add your handling code here:
        alCancelar();
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:

        if (comNom.getText().trim().equals("") && comKmCar.getText().trim().equals("") && comKmIni.getText().trim().equals("") && comKmFin.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Modificar esta información?", "Comunidad", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String modificacion = "update comunidad set nombre='" + comNom.getText().toUpperCase().trim() + "', kmCarretera='" + comKmCar.getText().trim() + "', kmInicio='" + comKmIni.getText().trim() + "', kmFin='" + comKmFin.getText().trim()  + "' where idcomunidad='"+comId.getText().trim() + "'";
                    ps = (PreparedStatement) con.prepareStatement(modificacion);
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro Modificado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        if (comNom.getText().trim().equals("") && comKmCar.getText().trim().equals("") && comKmIni.getText().trim().equals("") && comKmFin.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Guardar esta información?", "Comunidad", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String insercion = "insert into comunidad values(?,?,?,?,?)";
                    ps = (PreparedStatement) con.prepareStatement(insercion);
                    ps.setString(1, comId.getText().trim());
                    ps.setString(2, comNom.getText().toUpperCase().trim());
                    ps.setString(3, comKmCar.getText().trim());
                    ps.setString(4, comKmIni.getText().trim());
                    ps.setString(5, comKmFin.getText().trim());               
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicio abrir = new inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comNomKeyTyped
        // TODO add your handling code here:
        char letter = evt.getKeyChar();
        if((letter<'a'||letter>'z')&&(letter<'A'||letter>'Z')){
            evt.consume();
        }        
    }//GEN-LAST:event_comNomKeyTyped

    private void comIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comIdKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }        
    }//GEN-LAST:event_comIdKeyTyped

    private void comKmCarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comKmCarKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }        
    }//GEN-LAST:event_comKmCarKeyTyped

    private void comKmIniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comKmIniKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }        
    }//GEN-LAST:event_comKmIniKeyTyped

    private void comKmFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comKmFinKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }        
    }//GEN-LAST:event_comKmFinKeyTyped
    public void alCancelar()
    {
        cmdCancelar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdModificar.setEnabled(false);
        cmdBuscar.setEnabled(true);
        cmdBorrar.setEnabled(false);
        comNom.setEnabled(false);
        comId.setEnabled(true);
        comKmCar.setEnabled(false);
        comKmIni.setEnabled(false);
        comKmFin.setEnabled(false);
        comId.setText("");
        comNom.setText("");
        comKmCar.setText("");
        comKmIni.setText("");
        comKmFin.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comunidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comunidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JTextField comId;
    private javax.swing.JTextField comKmCar;
    private javax.swing.JTextField comKmFin;
    private javax.swing.JTextField comKmIni;
    private javax.swing.JTextField comNom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/1.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
    class FondoPanel2 extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/2.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }     
}
