/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author RODRIGO
 */
public class interseccion extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    FondoPanel2 fondo2 = new FondoPanel2();    
    private Connection con;
    Connect  conectar = new Connect();
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form interseccion
     */
    public interseccion() {
        this.setContentPane(fondo); 
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        intTra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        intCom = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        cmdBuscarCat = new javax.swing.JButton();
        jPanel1 = new FondoPanel2();
        jButton2 = new javax.swing.JButton();
        cmdBuscarCat1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        intId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATOS  INTERSECCIÓN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID DE TRAMO:");

        intTra.setEnabled(false);
        intTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID DE COMUNIDAD");

        intCom.setEnabled(false);
        intCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intComActionPerformed(evt);
            }
        });

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.setEnabled(false);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdModificar.setBackground(new java.awt.Color(255, 255, 0));
        cmdModificar.setText("Modificar");
        cmdModificar.setEnabled(false);
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdCancelar.setBackground(new java.awt.Color(255, 255, 0));
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systems/imgBorrar.png"))); // NOI18N
        cmdBorrar.setEnabled(false);
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdBuscar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        cmdBuscarCat.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscarCat.setText("...");
        cmdBuscarCat.setEnabled(false);
        cmdBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarCatActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        cmdBuscarCat1.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscarCat1.setText("...");
        cmdBuscarCat1.setEnabled(false);
        cmdBuscarCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarCat1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        intId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intIdActionPerformed(evt);
            }
        });
        intId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                intIdKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(intCom, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdGuardar)
                                .addGap(56, 56, 56)
                                .addComponent(cmdModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdCancelar)))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intTra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdBuscarCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBuscar)
                    .addComponent(cmdBuscarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cmdBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(intId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(intTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBuscarCat1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(intCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBuscarCat))
                        .addGap(18, 18, 18)
                        .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intTraActionPerformed

    private void intComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intComActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        if (intCom.getText().trim().equals("") && intTra.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Guardar esta información?", "Intersección", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String insercion = "insert into interseccón values(?,?,?)";
                    ps = (PreparedStatement) con.prepareStatement(insercion);
                    ps.setString(1, intId.getText().trim());
                    ps.setString(2, intTra.getText().trim());
                    ps.setString(3, intCom.getText().trim());
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:

        if (intTra.getText().trim().equals("") && intCom.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Modificar esta información?", "Intersección", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String modificacion = "update interseccón set idtramo='" + intTra.getText().trim() + "', idcomunidad='" + intCom.getText().trim() + "'";
                    ps = (PreparedStatement) con.prepareStatement(modificacion);
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro Modificado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        // TODO add your handling code here:
        alCancelar();
    }//GEN-LAST:event_cmdCancelarActionPerformed
    public void alCancelar()
    {
        cmdCancelar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdModificar.setEnabled(false);
        cmdBuscar.setEnabled(true);
        cmdBorrar.setEnabled(false);
        cmdBuscarCat.setEnabled(false);
        cmdBuscarCat1.setEnabled(false);
        intCom.setEnabled(false);
        intId.setEnabled(true);
        intTra.setEnabled(false);
        intId.setText("");
        intCom.setText("");
        intTra.setText("");
    }
    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Seguro quiere eliminar este registro?", "Intersección", JOptionPane.YES_NO_OPTION)==0)
        {
            try
            {
                con=conectar.getConexion();
                String eliminacion = "delete from interseccón where idinterseccion='" + intId.getText().trim() + "'" ;
                ps = (PreparedStatement) con.prepareStatement(eliminacion);
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado...");
                alCancelar();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        if(intId.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese un numero de ID");
        }else{
            String busqueda = "select * from interseccón where idinterseccón=" + intId.getText().trim();
            try
            {
                con=conectar.getConexion();
                st=(Statement) con.createStatement();
                rs=st.executeQuery(busqueda);
                while (rs.next())
                {
                    encontrado = true;
                    cmdModificar.setEnabled(true);
                    cmdGuardar.setEnabled(false);
                    cmdBorrar.setEnabled(true);
                    cmdBuscarCat.setEnabled(true);
                    cmdBuscarCat1.setEnabled(true);
                    intId.setText(rs.getString("idinterseccón"));
                    intTra.setText(rs.getString("idtramo"));
                    intCom.setText(rs.getString("idcomunidad"));
                }
                con.close();
                cmdCancelar.setEnabled(true);
                cmdBuscar.setEnabled(false);
                intId.setEnabled(false);
                intTra.setEnabled(false);
                intCom.setEnabled(false);
                if (encontrado == false){
                    cmdBuscarCat1.setEnabled(true);
                    cmdBuscarCat.setEnabled(true);
                    cmdGuardar.setEnabled(true);
                }

            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarCatActionPerformed
        // TODO add your handling code here:
        buscarComunidad buscaComunidad = new buscarComunidad();
        buscaComunidad.setVisible(true);
    }//GEN-LAST:event_cmdBuscarCatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicio abrir = new inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdBuscarCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarCat1ActionPerformed
        // TODO add your handling code here:
        buscarTramo buscaTramo = new buscarTramo();
        buscaTramo.setVisible(true);        
    }//GEN-LAST:event_cmdBuscarCat1ActionPerformed

    private void intIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intIdActionPerformed

    private void intIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intIdKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }        
    }//GEN-LAST:event_intIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interseccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdBuscarCat;
    private javax.swing.JButton cmdBuscarCat1;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    public static javax.swing.JTextField intCom;
    private javax.swing.JTextField intId;
    public static javax.swing.JTextField intTra;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/1.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
    
    class FondoPanel2 extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/2.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
}
