/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author RODRIGO
 */
public class tramo extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    FondoPanel2 fondo2 = new FondoPanel2();    
    private Connection con;
    Connect  conectar = new Connect();
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form tramo
     */
    public tramo() {
        this.setContentPane(fondo); 
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        traId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        traIni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        traFin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        traCar = new javax.swing.JTextField();
        cmdBorrar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        jPanel1 = new FondoPanel2();
        jButton2 = new javax.swing.JButton();
        cmdBuscarCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATOS  TRAMO");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        traId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traIdActionPerformed(evt);
            }
        });
        traId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                traIdKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KM INICIO:");

        traIni.setEnabled(false);
        traIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traIniActionPerformed(evt);
            }
        });
        traIni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                traIniKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KM FIN:");

        traFin.setEnabled(false);
        traFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                traFinKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID DE CARRETERA:");

        traCar.setEnabled(false);
        traCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traCarActionPerformed(evt);
            }
        });

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systems/imgBorrar.png"))); // NOI18N
        cmdBorrar.setEnabled(false);
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        cmdBuscar.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });

        cmdCancelar.setBackground(new java.awt.Color(255, 255, 0));
        cmdCancelar.setText("Cancelar");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdModificar.setBackground(new java.awt.Color(255, 255, 0));
        cmdModificar.setText("Modificar");
        cmdModificar.setEnabled(false);
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.setEnabled(false);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        cmdBuscarCat.setBackground(new java.awt.Color(255, 255, 0));
        cmdBuscarCat.setText("...");
        cmdBuscarCat.setEnabled(false);
        cmdBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(traCar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmdBuscarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(traId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmdBuscar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cmdGuardar)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmdModificar)
                                            .addGap(32, 32, 32)
                                            .addComponent(cmdCancelar)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(traFin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(traIni, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(traId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(traIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(traCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBuscarCat)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(traFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void traIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traIdActionPerformed

    private void traIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traIniActionPerformed

    private void traCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traCarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Seguro quiere eliminar este registro?", "Tramo", JOptionPane.YES_NO_OPTION)==0)
        {
            try
            {
                con=conectar.getConexion();
                String eliminacion = "delete from tramo where idtramo='" + traId.getText().trim() + "'" ;
                ps = (PreparedStatement) con.prepareStatement(eliminacion);
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado...");
                alCancelar();

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        if(traId.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese un numero de ID");
        }else{
            String busqueda = "select * from tramo where idtramo=" + traId.getText().trim();
            try
            {
                con=conectar.getConexion();
                st=(Statement) con.createStatement();
                rs=st.executeQuery(busqueda);
                while (rs.next())
                {
                    encontrado = true;
                    cmdModificar.setEnabled(true);
                    cmdGuardar.setEnabled(false);
                    cmdBorrar.setEnabled(true);
                    cmdBuscarCat.setEnabled(true);
                    traIni.setText(rs.getString("kmInicioCarretera"));
                    traFin.setText(rs.getString("kmFinCarretera"));
                    traCar.setText(rs.getString("idCarretera"));
                }
                con.close();
                cmdCancelar.setEnabled(true);
                cmdBuscar.setEnabled(false);
                traId.setEnabled(false);
                traIni.setEnabled(true);
                traFin.setEnabled(true);              
                if (encontrado == false){
                    cmdBuscarCat.setEnabled(true);
                    cmdGuardar.setEnabled(true);                    
                }

            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        }

    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        // TODO add your handling code here:
        alCancelar();
    }//GEN-LAST:event_cmdCancelarActionPerformed
    public void alCancelar()
    {
        cmdCancelar.setEnabled(false);
        cmdGuardar.setEnabled(false);
        cmdModificar.setEnabled(false);
        cmdBuscar.setEnabled(true);
        cmdBorrar.setEnabled(false);
        cmdBuscarCat.setEnabled(false);
        traIni.setEnabled(false);
        traId.setEnabled(true);
        traFin.setEnabled(false);
        traCar.setEnabled(false);
        traId.setText("");
        traIni.setText("");
        traFin.setText("");
        traCar.setText("");
    }
    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:

        if (traIni.getText().trim().equals("") && traFin.getText().trim().equals("") && traCar.getText().trim().equals(""))
            JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Modificar esta información?", "Tramo", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String modificacion = "update tramo set kmInicioCarretera='" + traIni.getText().trim() + "', kmFinCarretera='" + traFin.getText().trim() + "', idCarretera='" + traCar.getText().trim()  + "' where idtramo='"+traId.getText().trim() + "'";
                    ps = (PreparedStatement) con.prepareStatement(modificacion);
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro Modificado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        if (traIni.getText().trim().equals("") && traFin.getText().trim().equals("") && traCar.getText().trim().equals(""))
        JOptionPane.showMessageDialog(rootPane, "No puede dejar cuadros en blanco...");
        else
        {
            if (JOptionPane.showConfirmDialog(rootPane, "Guardar esta información?", "Tramo", JOptionPane.YES_NO_OPTION)==0)
            {
                try
                {
                    con=conectar.getConexion();
                    String insercion = "insert into tramo values(?,?,?,?)";
                    ps = (PreparedStatement) con.prepareStatement(insercion);
                    ps.setString(1, traId.getText().trim());
                    ps.setString(2, traIni.getText().trim());
                    ps.setString(3, traFin.getText().trim());
                    ps.setString(4, traCar.getText().trim());
                    ps.executeUpdate();
                    con.close();
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado...");
                    alCancelar();

                } catch (Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, e.toString());
                }
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inicio abrir = new inicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarCatActionPerformed
        // TODO add your handling code here:
        buscarCarretera buscaCarretera = new buscarCarretera();
        buscaCarretera.setVisible(true);
    }//GEN-LAST:event_cmdBuscarCatActionPerformed

    private void traIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traIdKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_traIdKeyTyped

    private void traIniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traIniKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_traIniKeyTyped

    private void traFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traFinKeyTyped
        // TODO add your handling code here:
        char NUM = evt.getKeyChar();
        if((NUM<'0'||NUM>'9')){
            evt.consume();
        }          
    }//GEN-LAST:event_traFinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tramo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tramo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdBuscarCat;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField traCar;
    private javax.swing.JTextField traFin;
    private javax.swing.JTextField traId;
    private javax.swing.JTextField traIni;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/1.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
    
    class FondoPanel2 extends JPanel{
        private Image imagen;
        @Override
         public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/image/2.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    
    }
}
